### ISSUE TITLE
Missing support for attachment name deduplication (same file across multiple emails)

### ISSUE THREAD

**Issue by davidesner** [pocin/kbc-ex-gmail-attachments#6]
Hi,

we wanted to use this extractor for our client and I discovered recently that when the query matches more emails and they both contain file with a same name (e.g. two days of data), it stores the file and overwrites a content of any already downloaded file with a same name.

Would it be possible to add a flag here, to allow a choice of appending `attachment_id` and current timestamp while building the `filename`  variable? 

https://github.com/pocin/kbc-ex-gmail-attachments/blob/5ae090d9b480bec26799ce4ec870791ad6551193/main.py#L85

https://github.com/pocin/kbc-ex-gmail-attachments/blob/5ae090d9b480bec26799ce4ec870791ad6551193/main.py#L90

Or more a complex solution to dedupe all files with a same name -> check whether the file already exist and then add some unique suffix. 

I would keep the suffix of the attachment if any, e.g. append it right before `.csv` 

I can submit a pull request if you like. 

Thanks a lot!

**Comment by pocin** [comment]
Hi David, good catch and that definitely is a bug!

Just one thing to bear in mind: If someone is not using processors to create sliced files , the filename affects the name of the table in kbc storage - adding a suffix to all attachments by default would probably break existing configurations.

The safest bet here might be to raise an error if one is not using processors and a duplicated attachment is found. If one is using processors we might assume he will be using 
```
   {
      "definition": {"component": "keboola.processor-move-files"},
      "parameters": {
        "direction": "tables",
        "folder": "tablename_in_storage.csv"
      }
    }
```
to handle sliced files and create a custom table name in Storage.

Do you see what I mean here? What do you think?

**Comment by davidesner** [comment]
HI, thanks for a quick answer! Yes I thought of that, that's why I thought maybe control that by a parameter. But your solution seems even better - in case the processors are not being used throw an error and notify user to adjust the query or use the processors. Processors might even dedupe by default. It would be nice to have that documented too. Thanks!

**Comment by pocin** [comment]
Ok I will make make a PR now, should be simple

**Comment by pocin** [comment]
@davidesner according to my tests it should be working and should be live in kbc in couple mins. lmk if things work out well for you!
