### ISSUE TITLE
The extractor sometimes does not download the attachements

### ISSUE THREAD

**Issue by KovarJ** [pocin/kbc-ex-gmail-attachments#8]
Hello Robin,
I wrote on Keboola support, but I realized I can reach you here. I have noticed that sometimes, nothing is extracted from Gmail messages, although the messages are there and the attachements are also there. Everything works fine, till the emails are sent from automated reporting (in my case, Toyota I-Site ) - then the extractor does not find the file. If I send it to from my other email, everything works fine.
I suppose I found the error in the extractor, as I was experimenting with extracting files from gmail myself (although your solution is much more elegant).
The problem with your extractor is that the program goes through the gmail message "parts" only once looking for filename. However it is possible that "parts" has "parts" itself (oh god, this sounds really weird).
I tried to explain on screenshots of relevant code.

![error_in_gmail_extractor](https://user-images.githubusercontent.com/50369547/58708580-79ab4780-83b8-11e9-9913-aa27fdd588e4.png)
![my_solution](https://user-images.githubusercontent.com/50369547/58708579-79ab4780-83b8-11e9-9dca-1bf6aa67c33e.png)

It would be great if you could solve this, because I really want to use your extractor - and now it is impossible for me.
Thanks!
Jakub

**Comment by pocin** [comment]
Hi Kubo,
do you think you can attach an anonymized json of that `message` from your code? I admit I can't really imagine it actually look like? Or illustrate it on this here https://developers.google.com/gmail/api/v1/reference/users/messages
Or if you could somehow forward me such email (to `robin(at)meiro.io`) I could test it out.
Without that in hand the only thing I can do is accept a pull request you make (assuming it doesn't break existing behavior).

Let me know,
Robin

**Comment by pocin** [comment]
Sorry I can't reproduce it, what you sent me works just fine.

**Comment by KovarJ** [comment]
Sent you also the .json and I tried to elaborate on it.

**Comment by pocin** [comment]
@KovarJ sorry for the wait, but you know, Mondays.. :-)  The build just finished and a new version of the extractor should be deployed in keboola in about 5 minutes. Please test it out and let me know

**Comment by KovarJ** [comment]
Hi Robin, sure, I understand :-) I tried in Keboola and sadly the problem persists:
![image](https://user-images.githubusercontent.com/50369547/58871623-b0d46e00-86c2-11e9-9fc3-f3786e2b6ef6.png)
![image](https://user-images.githubusercontent.com/50369547/58871733-deb9b280-86c2-11e9-807f-f59498383261.png)
![image](https://user-images.githubusercontent.com/50369547/58871767-eda06500-86c2-11e9-96ce-22baa6ec0955.png)

Can't understand why - might be that the nesting is deeper than expected, so while would be better than for? Just guessing.
